// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://replbpgnctxmgogsfzad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcGxicGduY3R4bWdvZ3NmemFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NzEyMzIsImV4cCI6MjA1MDU0NzIzMn0.avy7RSRz067inPCJUoYqIO-FWkSlNjvLTYGQqSMW8LU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);